### ISSUE TITLE
package development

### ISSUE THREAD

**Issue by dicook** [tprvan/brolgar#3]
- [x]  add short example code for each function
- [x] add function for computing "quantiles", min, q1, median, q3, max to package
- [ ] add new indexes for measuring other types of structure in longitudinal data - need to find out important things
- [ ] add functions for pulling middle X% of subjects, or the A% to B% of subjects. this would enable more than a single subject to be examined - might be useful

**Comment by njtierney** [comment]
Moved these out to separate issues
